### ISSUE TITLE
Who should be responsible for triaging PRs in this repository?

### ISSUE THREAD

**Issue by galargh** [filecoin-shipyard/github-mgmt#9]
Open question - who should be taking care of GitHub Management on the filecoin side of things. Uncovered in https://github.com/filecoin-shipyard/github-mgmt/pull/7#issuecomment-1214611553

**Comment by galargh** [comment]
We have a GitHub Management Stewards team set up for this repository now.

**Comment by rvagg** [comment]
fwiw I've been the main one with my eyes across active stuff in this org; but that's mostly a maintenance thing, merging dependabot stuff, answering the occasional question, but it's been pretty quiet, especially since I archived a bunch of stuff last year
